apiVersion: v1
kind: Service
metadata:
  name: kubernete-demo-api-service
  labels:
    app: kubernete-demo-api
spec:
  selector:
    app: kubernete-demo-api
  ports:
    - protocol: TCP
      port: 3000 # Service port
      targetPort: 3000 # Container port
  type: NodePort # change to LoadBalancer if using a cloud provider that supports it